version: '3.8'

services:
  postgres_db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: prisma
    ports:
      - '5432:5432'